version: '3.8'

services:
  bot:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - SERVER_ADDRESS=:8080
      - DB_FILE=/data/queue.db
      - WORK_START=09:00
      - WORK_END=18:00
      - SLOT_DURATION=30
      - SCHEDULE_DAYS=7
      - SKIP_WEEKEND=1
      - RATE_LIMIT=60
      - SLOTS_PER_ROW=3
      - ADMIN_IDS=${ADMIN_IDS}
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    restart: unless-stopped
